# Generated by Django 3.0.8 on 2020-08-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part2', '0003_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='language',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='level',
            field=models.CharField(max_length=15),
        ),
    ]
